// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucwbdmejtygvxgzxijyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjd2JkbWVqdHlndnhnenhpanlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzU3MDQsImV4cCI6MjA2MTYxMTcwNH0.B8PkyxN3f-OQxGZIE9xK8DJcq63CK8ahhyybWb1Jo2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);